### ISSUE TITLE
Get element in methods.

### ISSUE THREAD

**Issue by sainf** [rachmanzz/vue-inview#10]
How can we get the current element triggered when we call something like.
```
<div v-inview:enter="methods"></div>
```

**Comment by rachmanzz** [comment]
when your element entered on viewport :
`<div v-inview:enter="callme"></div>`
methods (callme) will be called.

  ```
methods: {
    callme (el) {
        // el is your element
         console.log('element has been view')
    }
  }
```

**Comment by sainf** [comment]
Thanks!!
