### ISSUE TITLE
'querySelectorAll' error with class names

### ISSUE THREAD

**Issue by wienska** [rachmanzz/vue-inview#12]
Hi! Is there any way to forbid adding classes to the elements with v-inview? Because it adds classes that can start with numbers, I get the following error:

`DOMException: Failed to execute 'querySelectorAll' on 'Document': '.35YItMYvg2' is not a valid selector.`

**Comment by rachmanzz** [comment]
I have update new version that start with inview prefix.

**Comment by wienska** [comment]
Thanks!
