### ISSUE TITLE
How can I check if an element is fully viewed

### ISSUE THREAD

**Issue by averichev** [rachmanzz/vue-inview#14]
How can I check if an element is fully viewed if it does not fit on the screen (more than the viewport).

That is, for example, I have to understand that the user has scrolled the item from beginning to end

**Comment by rachmanzz** [comment]
please check at https://github.com/camwiegert/in-view#inviewthresholdthreshold and https://github.com/rachmanzz/vue-inview#vue-instance

using threshold you can set ratio of an element's height and width that needs to be visible.

**Comment by rachmanzz** [comment]
because no anwer, I think you have get solution.
