### ISSUE TITLE
Offset and threshold are undefined

### ISSUE THREAD

**Issue by samuells** [rachmanzz/vue-inview#15]
I tried to setup the offset, but I will get always undefined.

My setup as Nuxt Plugin
```
import Vue from 'vue'
import Inview from 'vueinview'
Inview.offset({
  top: 100,
  right: 75,
  bottom: 50,
  left: 25
})

Vue.use(Inview)
`

**Comment by rachmanzz** [comment]
I'm not sure what is error in your project. you can see this one first
https://codesandbox.io/embed/billowing-smoke-1rg4h?fontsize=14&hidenavigation=1&theme=dark

**Comment by samuells** [comment]
Thx for the sample and test. I will investigate further .. I am using directive directly as Nuxt Plugin but that shouldn't change anything.

**Comment by samuells** [comment]
I found it! I did set `ssr: true` for the directive, but it works only on client. So my mistake .. one more time thx for help and you can close this one. 🎄

**Comment by rachmanzz** [comment]
Ok. next time, I'll try run in nuxt, I think should work although you run in server side render.

**Comment by chrisjansky** [comment]
Hey @samuells,
may I ask what exactly did you have to specify to make it work with Nuxt? I am getting the same error when I try to access Inview.threshold(). Thank you!

**Comment by rachmanzz** [comment]
Noted, I will let you know, If I find a solution.

**Comment by rachmanzz** [comment]
this should work
```
import Vue from 'vue'
import inview from 'vueinview'
if (process.client) inview.offset({top: 100})
Vue.use(inview)
```
