### ISSUE TITLE
yarn check fails

### ISSUE THREAD

**Issue by UthpalaHeenatigala** [rachmanzz/vue-inview#16]
I get the following errors. 

error "gulp-uglify#uglify-js" is wrong version: expected "3.7.4", got "3.4.10"
error "uglify-js#commander" is wrong version: expected "2.20.3", got "2.19.0"
error "html-minifier#uglify-js" not installed
error "html-minifier#uglify-js#commander" not installed

**Comment by rachmanzz** [comment]
I'm not sure, what is the error. I can't check by my self now. But maybe you can check your nodejs version and yarn version. If your have install nodejs lower from stable version, please update your nodejs.

**Comment by UthpalaHeenatigala** [comment]
node version - v12.14.0
yarn version - 1.21.1

running yarn check I get the following errors 

error "gulp-uglify#uglify-js" is wrong version: expected "3.7.4", got "3.4.10"
error "uglify-js#commander" is wrong version: expected "2.20.3", got "2.19.0"
error "html-minifier#uglify-js" not installed
error "html-minifier#uglify-js#commander" not installed

I only get these errors after installing vue-inview

**Comment by rachmanzz** [comment]
maybe you can check new update.  vueinview version 1.0.7 release
