### ISSUE TITLE
How to set Offset

### ISSUE THREAD

**Issue by mittelgrau** [rachmanzz/vue-inview#2]
Hey just a simple - maybe uninformed/stupid question - could you please describe how to correctly set a Offset Value. I tried it like this:  

```
import Inview from 'vue-inview';
Vue.use(Inview);

Inview.threshold('100px')
Inview.offset('1000px');
```

Could you tell me what I did wrong. Kinda confused by your documented way with 

```
// v_inview.offset(/* offset */)
// v_inview.threshold(/* threshold */)

```
Keep up the good work 💯 !

**Comment by rachmanzz** [comment]
offset value must be number or object

  ` Inview.offset(100) `
or

  ```
 Inview.offset({
      top: 100,
      right: 75,
      bottom: 50,
      left: 25
   }) 
```

if you using threshold, value is number between 0-1
example: 

`  Inview.threshold(0.5)`
