### ISSUE TITLE
ONly addinging class on first load... not on scroll

### ISSUE THREAD

**Issue by rjcdigital** [rachmanzz/vue-inview#22]
HI, Firstly i thnk this libary is great.  Thanks very much!

I have this: v-inview:class="['a-inview--active']"

on a load of different elements.  it works when the page first renders.

But when i scroll new elements into view, the class is not added.

Do i need to add some directive to teh scrolling parent to make it work?  if i rotate my screen and back it seems to work... just not when i scroll. my container.

Please can you advise?  thanks in advance.

**Comment by rachmanzz** [comment]
Hy @rjcdigital, please describe more detail and please attach your example code.
this documentation should help you
https://github.com/rachmanzz/vue-inview/tree/v1.0.7#class--style

or you can custom by yourself, follow this component
https://github.com/rachmanzz/vue-inview/blob/v1.0.7/components/Inview.vue
you may need to see this documentation:
https://github.com/rachmanzz/vue-inview/tree/v1.0.7#components-new
