### ISSUE TITLE
Custom animations

### ISSUE THREAD

**Issue by Christilut** [rachmanzz/vue-inview#3]
I like the integrations with animate.css but it doesn't quite have the animations I want. How can I easily add custom animations?  It doesn't seem to recognize my own animations.

**Comment by rachmanzz** [comment]
if you need implement your own custom animation, you can use class directive.
example :
`<div v-inview:class="['youranimationClass']"></div>`

**Comment by Christilut** [comment]
Thanks

**Comment by rachmanzz** [comment]
Feel free to ask me, if you need something new.
