### ISSUE TITLE
Uncaught ReferenceError: _$mdf is not defined

### ISSUE THREAD

**Issue by adamduncan** [rachmanzz/vue-inview#4]
We're getting an `Uncaught ReferenceError: _$mdf is not defined` as elements `exit`

Is this a typo, and should be `$mdf`?

![image](https://user-images.githubusercontent.com/2671053/31014370-64abd484-a512-11e7-8ecf-41d79cf14339.png)

https://github.com/rachmanzz/vue-inview/blob/5dee157a7d22de08bc5bf267a724869b78b20761/dist/vue-inview.js#L584

Using master v1.0.2

Thanks

**Comment by rachmanzz** [comment]
sorry, wrong type underscore. I have update package in github.
reinstall vueinview from github directly. 
`npm install rachmanzz/vue-inview`

**Comment by adamduncan** [comment]
Perfect! Thanks for patching that so fast 👍 

A fresh `npm install` has done the job.
