### ISSUE TITLE
firing on component load

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [rachmanzz/vue-inview#5]
Why are the inview firing first time the page loads?

main.js file

```javascript
import Inview from 'vueinview'
Vue.use(Inview)
Inview.offset(100)
// Inview.threshold(0.3)
```

Home.vue

```javascript

<div style='height: 100vh;'></div>
<div v-inview:once='triggerMethod'></div>

...

methods: {
   triggerMethod() {
      console.log('hello there')
   }
}
```

When the page load i get 'hello there' in the console, but the div isnt in the view

Obs: using this source -> github:rachmanzz/vue-inview

**Comment by diego-lipinski-de-castro** [comment]
Ok, I did not realized I should put el.enter to every inview directive, my bad

**Comment by averichev** [comment]
How did you solve the problem? I have the same

**Comment by rachmanzz** [comment]
take look at https://github.com/rachmanzz/vue-inview#vue-instance

         

```
triggerMethod(action) {
              action.enter = (el) => {
                  // code
              }
              action.exit = (el) => {
                 // code
              }
         }
```

**Comment by averichev** [comment]
@rachmanzz thank you very much

By the way

How can I check if an element is fully viewed if it does not fit on the screen (more than the viewport).

That is, for example, I have to understand that the user has scrolled the item from beginning to end
