### ISSUE TITLE
ie9 compatibility

### ISSUE THREAD

**Issue by Zae** [rachmanzz/vue-inview#6]
Hi,

You plugin is using classList which is sadly not understood in ie9.

luckily there is a polyfill for that: classlist-polyfill

Up to you if you want to include it in your library yourself or maybe nice to add in the README that if you need ie9 support you need to include the polyfill as well.

**Comment by rachmanzz** [comment]
Thanks for your information. 
I am open to other contributions.
I don't have lot time to some revision, there many project that I have handling.
If you feel you can do it ( for some contribution ), I so glad to you
