### ISSUE TITLE
High CPU usage in "Magic properties"

### ISSUE THREAD

**Issue by sainf** [rachmanzz/vue-inview#9]
First thanks for making the wrapper.

If we use like the readme the "Magic properties" it causes high CPU  "sync".
Check in chromedev and find the culprit... 
```
/**
  * (update → function)
    - life cycle update
**/
var updateLifeCycle = function (update) {
  var sync = function () {
    update()
    setTimeout(sync,0)
  }
  sync()
}
```
Perhaps increase the setTimeout?

**Comment by rachmanzz** [comment]
Magic properties is not recommended to use, you can use the other choice like `v-inview:on` is same return. 
` updateLifeCycle` is always run when `_$inview` called.

**Comment by sainf** [comment]
Ok, I'll remove the Magic properties from my code, thanks!
